version: '3.7'

services:
  web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000
    environment:
      - SECRET_KEY=tfkc%89_0x01y43bsp3u&d!semwurr!7@&i2h(1yo@*r@sd!op
      - DEBUG=1
      - EMAIL_HOST=smtp-relay.brevo.com
      - EMAIL_HOST_USER=mukundamhasalkar@gmail.com
      - EMAIL_HOST_PASSWORD=dV1LZKG8q3s6gQCz
      - EMAIL_PORT=587
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
  
  db:
    image: postgres:11
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: "db"
      POSTGRES_HOST_AUTH_METHOD: "trust"

volumes:
  postgres_data:
